// eslint-disable-next-line @next/next/no-img-element

import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../app/components/Navbar"
import Footer from "./components/Footer";

const montserratWght = localFont({
  src: "./fonts/MontserratWght.woff2",
  variable: "--font-Montserrat-Wght",
  weight: "100 900",
});
const milkerRegular = localFont({
  src: "./fonts/Milker.woff2",
  variable: "--font-Milker-Regular",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="es">
      <body className={`${montserratWght.variable} ${milkerRegular.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
